name: Discord Chatbot Heroku Deployment

on:
  - push
  - pull_request

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt

    - name: Linting with flake8
      run: |
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=200 --statistics

    - name: Pre-commit hook
      run: |
        python -m pip install --upgrade pre-commit
        pre-commit run --verbose --all-files --show-diff-on-failure

  deployment:
    name: Deploy
    needs: [test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request_review'
    steps:
    - uses: actions/checkout@v3
    - name: Deploy to Heroku
      env:
        HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
        HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      run: |
        git fetch --prune --unshallow
        git remote add heroku https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git
        git push heroku HEAD:main -f
